version: '3.5'

services:
  fpm:
    restart: always
    build:
      context: .
      dockerfile: ./docker/fpm/Dockerfile
    volumes:
      - ./:/var/www/url-minifier:rw,cached
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'service'
    ports:
      - '9000:9000'

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
      - '443:433'
    depends_on:
      - fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
      - ./:/var/www/url-minifier:ro,cached

  mysql:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'service'
